# Generated by Django 5.0.1 on 2024-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('yearsExperience', models.CharField(max_length=500)),
                ('happyCustomers', models.CharField(max_length=500)),
                ('projectsfinished', models.CharField(max_length=500)),
                ('digitalAwards', models.CharField(max_length=500)),
                ('dateTime', models.CharField(max_length=500)),
            ],
        ),
    ]
