# Generated by Django 5.0.1 on 2024-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secdemport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='projectsfinished',
            new_name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='projectsFinished',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
